updated setup to house all configuration, and replaced options with sane-defaults via detection

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,28 +1,132 @@
 #!/bin/bash
 
 # query for options
-while [ "$service" != "template" ] && [ "$service" != "web" ] && [ "$service" != "dev" ] && [ "$service" != "osx" ] && [ "$service" != "windows" ]
-do
-    echo -n "what type of system is this (template|web|dev|osx|windows)? "
-    read service
-done
+if [ $(uname) = "Linux" ]
+then
 
+    ##
+    # fail if not running as root
+    ##
+    [ $(id -u) -ne 0 ] && echo "must be executed with root permissions..." && exit 1
+
+
+    ##
+    # ask platform specific questions
+    ##
+
+    while [ "$service" != "template" ] && [ "$service" != "web" ] && [ "$service" != "dev" ]
+    do
+        echo -n "what type of system is this (template|web|dev)? "
+        read service
+    done
+
+    while [ -z "$username" ]
+    do
+        echo -n "enter a username for your new system user: "
+        read username
+    done
+
+    while [ -z "$password" ]
+    do
+        echo -n "enter a password for your new system user: "
+        read password
+    done
+
+    echo -n "enter an ssh port (default: 22): "
+    read ssh_port
+
+    echo -n "enter a hostname (default: $service): "
+    read system_hostname
+
+    echo -n "enter a domain name (optional): "
+    read domainname
+
+    echo -n "enter a timezone path (default: /usr/share/zoneinfo/US/Eastern): "
+    read timezone
+
+    while [ "$jis" != "n" ] && [ "$jis" != "y" ]
+    do
+        echo -n "enable jis (y|n): "
+        read jis
+    done
+
+    while [ "$create_ssh" != "n" ] && [ "$create_ssh" != "y" ]
+    do
+        echo "would you like to generate an ssh key (y|n)?"
+        read create_ssh
+    done
+
+
+    ##
+    # request service specific settings
+    ##
+
+
+    ##
+    # set platform defaults
+    ##
+    [ -z "$ssh_port" ] && ssh_port=22
+    [ -z "$timezone" ] && timezone="/usr/share/zoneinfo/US/Eastern"
+    [ -z "$system_hostname" ] && system_hostname=$service
+
+elif [ $(uname) = "Darwin" ]
+then
+    service="osx"
+
+
+    ##
+    # ask platform specific questions
+    ##
+
+    while [ "$jis" != "n" ] && [ "$jis" != "y" ]
+    do
+        echo -n "enable jis (y|n): "
+        read jis
+    done
+
+    while [ "$create_ssh" != "n" ] && [ "$create_ssh" != "y" ]
+    do
+        echo "would you like to generate an ssh key (y|n)?"
+        read create_ssh
+    done
+
+
+    ##
+    # set platform specific settings
+    ##
+
+elif [[ $(name) = MINGW* ]]
+then
+    service="windows"
+
+
+    ##
+    # ask platform specific questions
+    ##
+
+    while [ "$create_ssh" != "n" ] && [ "$create_ssh" != "y" ]
+    do
+        echo "would you like to generate an ssh key (y|n)?"
+        read create_ssh
+    done
+
+
+    ##
+    # set platform specific settings
+    ##
+
+else
+    echo "no scripts for this platform..."
+    exit 1
+fi
+
+##
+# ask platform agnostic questions
+##
 while [ "$dot_files" != "n" ] && [ "$dot_files" != "y" ]
 do
     echo -n "install dot-files (y|n)? "
     read dot_files
-done
-
-while [ -z "$username" ]
-do
-    echo -n "enter a username for your new system user: "
-    read username
-done
-
-while [ -z "$password" ]
-do
-    echo -n "enter a password for your new system user: "
-    read password
 done
 
 echo -n "enter a github username for the configuration (optional): "
@@ -31,19 +135,20 @@ read github_username
 echo -n "enter a github password for the configuration (optional): "
 read github_password
 
-# set defaults
+
+##
+# set default values for scripted execution
+##
+
 remote_source="https://raw.githubusercontent.com/cdelorme/system-setup/develop/"
 [ -z "$service" ] && service="template"
 [ "$dot_files" = "y" ] && dot_files="https://raw.githubusercontent.com/cdelorme/dot-files/master/install"
 
-# stop if no username and password are supplied
-if [ -z "$username" ] || [ -z "$password" ]
-then
-    echo "please supply a new system user and password..."
-    exit 1
-fi
 
-# assume a default download command for grabbing files during processing
+##
+# verify available remote commands
+##
+
 if which curl &> /dev/null
 then
     dl_cmd="curl -Lo"
@@ -54,22 +159,11 @@ then
     source_cmd="--no-check-certificate -qO-"
 fi
 
-# load next service script
-if [ "$service" = "template" ]
-then
-    [ -f "scripts/template.sh" ] && . "scripts/template.sh" || . <($source_cmd "${remote_source}scripts/template.sh")
-elif [ "$service" = "web" ]
-then
-    [ -f "scripts/web.sh" ] && . "scripts/web.sh" || . <($source_cmd "${remote_source}scripts/web.sh")
-elif [ "$service" = "dev" ]
-then
-    [ -f "scripts/dev.sh" ] && . "scripts/dev.sh" || . <($source_cmd "${remote_source}scripts/dev.sh")
-elif [ "$service" = "osx" ]
-then
-    [ -f "scripts/osx.sh" ] && . "scripts/osx.sh" || . <($source_cmd "${remote_source}scripts/osx.sh")
-elif [ "$service" = "windows" ]
-then
-    [ -f "scripts/windows.sh" ] && . "scripts/windows.sh" || . <($source_cmd "${remote_source}scripts/windows.sh")
-fi
 
+##
+# load service script
+##
+
+echo "loading $service script..."
+[ -f "scripts/${service}.sh" ] && . "scripts/${service}.sh" || . <($source_cmd "${remote_source}scripts/${service}.sh")
 echo "finished setup..."
